"""Offline smoke check; run in the built container with --network none."""
import importlib.util,json,os,subprocess,tempfile,time
from pathlib import Path
from urllib.request import Request,urlopen
root=Path(__file__).resolve().parents[1]
spec=importlib.util.spec_from_file_location('bootstrap',root/'scripts/initialize.py')
b=importlib.util.module_from_spec(spec);spec.loader.exec_module(b)
with tempfile.TemporaryDirectory() as tmp:
 b.initialize(tmp,{},'fictional-smoke-password','https://example.invalid/fixture.yaml')
 runtime=Path(tmp)/'runtime';data=runtime/'control-center'
 # dnsmasq --test parses configuration without listening or starting DHCP.
 (data/'dnsmasq.conf').write_text(b.Settings().dnsmasq(data))
 if os.environ.get('NDF_SMOKE_FOREIGN_UID'):
  # Model private configuration generated by a non-root NAS account (0700/0600).
  uid=int(os.environ['NDF_SMOKE_FOREIGN_UID'])
  for path in [runtime,*runtime.rglob('*')]:os.chown(path,uid,uid)
 subprocess.run(['dnsmasq','--test','--conf-file='+str(data/'dnsmasq.conf')],check=True)
 env=dict(os.environ,NDF_DATA_ROOT=str(runtime))
 process=subprocess.Popen(['python3','/app/server.py'],env=env,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 try:
  for _ in range(30):
   try:
    with urlopen('http://127.0.0.1:9080/health',timeout=1) as r:assert json.load(r)=={'ok':True}
    break
   except OSError:time.sleep(.1)
  else:raise RuntimeError('controller did not become healthy')
  req=Request('http://127.0.0.1:9080/api/login',data=json.dumps({'password':'fictional-smoke-password'}).encode(),headers={'Content-Type':'application/json'})
  with urlopen(req,timeout=2) as r:assert r.status==200 and 'csrf' in json.load(r)
  assert not (data/'dhcp.enabled').exists()
  print('PASS: dnsmasq syntax, controller startup, health, login, DHCP remains OFF')
  if os.environ.get('NDF_SMOKE_FOREIGN_UID'):print('PASS: private non-root-owned runtime remains readable with DAC_OVERRIDE')
 finally:
  process.terminate();process.wait(timeout=10)
 # Browser setup entry point runs without a Docker socket or network privileges.
 setup_root=Path(tmp)/'setup';setup_root.mkdir()
 setup_env=dict(os.environ,NDF_SETUP_WORKSPACE=str(setup_root),NDF_PROJECT_PATH='/volume1/docker/fictional-install',NDF_SETUP_PORT='9098')
 setup_process=subprocess.Popen(['python3','-c',"import setup_server; setup_server.CODE='fictional-setup-code'; setup_server.main()"],env=setup_env,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 try:
  for _ in range(30):
   try:
    with urlopen('http://127.0.0.1:9098/health',timeout=1) as r:assert json.load(r)=={'ok':True}
    break
   except OSError:time.sleep(.1)
  else:raise RuntimeError('browser installer did not become healthy')
  req=Request('http://127.0.0.1:9098/api/login',data=json.dumps({'code':'fictional-setup-code'}).encode(),headers={'Content-Type':'application/json','Origin':'http://127.0.0.1:9098'})
  with urlopen(req,timeout=2) as r:assert r.status==200 and 'csrf' in json.load(r)
  assert not (setup_root/'runtime').exists()
  assert Path('/app/setup.html').exists() and Path('/app/compose.template.yaml').exists()
  print('PASS: browser installer image entry point, health, login, no runtime/DHCP changes')
 finally:
  setup_process.terminate();setup_process.wait(timeout=10)
